# from . import product_image
from . import res_company
from . import bigcommerce_order_status
from . import bc_store_listing
from . import bc_store_listing_item
from . import payment_transaction
from . import bigcommerce_store_configuration
from . import warehouse
from . import bigcommerce_operation_details
from . import bc_product_brand
from . import bc_payment_journal
from . import product_category
from . import product_attribute
from . import product_product
from . import product_template
from . import res_partner
from . import account_payment
from . import sale_order
from . import delivery_carrier
from . import stock
from . import bigcommerce_product_image
from . import bigcommerce_customer_group
