# -*- coding: utf-8 -*-pack
{       # App information
        'name': 'Custom Shipping Cost Calculation',
        'category': 'Website',
        'version': '15.26.05.2022',
        'summary': """""",
        'description': """Custom cost calculation offers reliable shipping solutions for multiple countries. If you use Odoo and third party carrier for your order shipments and you want's to take your own price according to product, shipping cost per product becomes absolutely crucial for you.""",
        'depends': ['delivery'],
        'data': ['views/delivery_carrier.xml',
             'data/shipment_tracking_mail_template.xml',
             'views/res_company.xml'],
        'images': ['static/description/cover.png'],
        'live_test_url': 'http://www.vrajatechnologies.com/contactus',
        'author': 'Vraja Technologies',
        'maintainer': 'Vraja Technologies',
        'website':'www.vrajatechnologies.com',
        'demo': [],
        'installable': True,
        'application': True,
        'auto_install': False,
        'price': '121',
        'currency': 'EUR',
        'license': 'OPL-1',
}